spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/quiz
    username: quiz
    password: quiz

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50

  flyway:
    enabled: true

server:
  port: 8080