INSERT INTO topic (slug, name, description, parent_uuid, status, sort_order,
                   created_at, updated_at, published_at)
VALUES ('java-core',
        'Java Core',
        'Основы языка Java и стандартной библиотеки.',
        NULL,
        'PUBLISHED',
        10,
        now(),
        now(),
        now()),
       ('collections',
        'Collections',
        'Коллекции и структуры данных Java.',
        NULL,
        'PUBLISHED',
        20,
        now(),
        now(),
        now()),
       ('concurrency',
        'Многопоточность',
        'Потоки, синхронизация и инструменты java.util.concurrent.',
        NULL,
        'PUBLISHED',
        30,
        now(),
        now(),
        now()),
       ('java-oop',
        'OOP',
        'Объектно-ориентированное программирование в Java.',
        (SELECT uuid FROM topic WHERE slug = 'java-core'),
        'PUBLISHED',
        10,
        now(),
        now(),
        now());

INSERT INTO question (topic_uuid, slug, question, reference_answer, explanation, question_type,
                      level_id, status, created_at, updated_at, published_at)
VALUES ((SELECT uuid FROM topic WHERE slug = 'java-core'),
        'what-is-jvm',
        'Что такое JVM?',
        'JVM (Java Virtual Machine) — виртуальная машина, которая выполняет байткод Java.',
        'JVM обеспечивает выполнение Java-программ независимо от конкретной операционной системы.',
        'SELF_ASSESSMENT',
        1,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'java-core'),
        'difference-between-jdk-jre-jvm',
        'Чем отличаются JDK, JRE и JVM?',
        'JVM выполняет байткод, JRE содержит JVM и необходимые библиотеки для запуска приложений, а JDK дополнительно содержит инструменты разработки.',
        'JDK используется для разработки, JRE — для запуска, JVM — для непосредственного выполнения байткода.',
        'SELF_ASSESSMENT',
        2,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'java-core'),
        'what-is-immutability',
        'Что означает неизменяемость объекта?',
        'Неизменяемый объект нельзя изменить после его создания. При необходимости создаётся новый объект.',
        'Неизменяемость упрощает работу с объектами в многопоточном коде и позволяет безопасно передавать их между частями программы.',
        'SELF_ASSESSMENT',
        2,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'collections'),
        'arraylist-vs-linkedlist',
        'Чем ArrayList отличается от LinkedList?',
        'ArrayList хранит элементы в массиве и эффективно обращается к элементам по индексу. LinkedList использует связанные узлы и имеет другие характеристики вставки и удаления.',
        'На практике ArrayList обычно является предпочтительным выбором, когда не требуется специфическое поведение LinkedList.',
        'SELF_ASSESSMENT',
        2,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'collections'),
        'how-hashmap-works',
        'Как работает HashMap?',
        'HashMap использует хеширование ключа для определения позиции элемента во внутренней структуре данных.',
        'При коллизиях несколько ключей могут находиться в одной позиции и обрабатываются специальным механизмом.',
        'SELF_ASSESSMENT',
        3,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'collections'),
        'hashset-vs-hashmap',
        'Чем HashSet отличается от HashMap?',
        'HashSet хранит уникальные элементы, а HashMap хранит пары ключ-значение.',
        'HashSet реализует множество, а HashMap — отображение ключей на значения.',
        'SELF_ASSESSMENT',
        1,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'concurrency'),
        'what-is-thread',
        'Что такое поток выполнения?',
        'Поток — независимая последовательность выполнения инструкций внутри процесса.',
        'Несколько потоков одного процесса могут выполнять работу конкурентно и разделять общую память.',
        'SELF_ASSESSMENT',
        1,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'concurrency'),
        'synchronized-keyword',
        'Для чего используется synchronized?',
        'synchronized обеспечивает взаимное исключение и синхронизацию доступа к критической секции.',
        'Он позволяет защитить общий ресурс от одновременного выполнения несколькими потоками.',
        'SELF_ASSESSMENT',
        2,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'concurrency'),
        'what-is-deadlock',
        'Что такое deadlock?',
        'Deadlock — ситуация, когда несколько потоков блокируют друг друга и ни один из них не может продолжить выполнение.',
        'Частая причина deadlock — циклическое ожидание ресурсов, захваченных разными потоками.',
        'SELF_ASSESSMENT',
        3,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'java-oop'),
        'four-principles-of-oop',
        'Какие четыре основных принципа ООП выделяют?',
        'Абстракция, инкапсуляция, наследование и полиморфизм.',
        'Эти принципы используются для организации объектной модели программы.',
        'SELF_ASSESSMENT',
        1,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'java-oop'),
        'what-is-polymorphism',
        'Что такое полиморфизм?',
        'Полиморфизм позволяет работать с объектами разных типов через общий интерфейс или базовый тип.',
        'В Java полиморфизм проявляется, в частности, при переопределении методов.',
        'SELF_ASSESSMENT',
        2,
        'PUBLISHED',
        now(),
        now(),
        now());

INSERT INTO question (topic_uuid, slug, question, reference_answer, explanation, question_type, level_id,
                      status, created_at, updated_at, published_at)
VALUES ((SELECT uuid FROM topic WHERE slug = 'java-core'),
        'which-type-is-immutable',
        'Какой из следующих типов является неизменяемым?',
        'String является неизменяемым классом в Java.',
        'После создания объекта String его состояние нельзя изменить. Операции изменения строки создают новый объект.',
        'SINGLE_CHOICE',
        1,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'collections'),
        'collection-interface-implementations',
        'Какие из следующих классов реализуют интерфейс List?',
        'ArrayList и LinkedList реализуют интерфейс List.',
        'Оба класса являются реализациями List, но используют разные внутренние структуры данных.',
        'MULTIPLE_CHOICE',
        2,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'java-core'),
        'match-java-types',
        'Сопоставьте тип Java с его характеристикой.',
        NULL,
        'Каждый тип имеет характерное назначение и поведение.',
        'MATCHING',
        1,
        'PUBLISHED',
        now(),
        now(),
        now()),
       ((SELECT uuid FROM topic WHERE slug = 'concurrency'),
        'thread-lifecycle-order',
        'Расположите состояния потока Java в порядке перехода от создания к завершению.',
        NULL,
        'Жизненный цикл потока проходит через последовательность состояний, определённых Thread.State.',
        'ORDERING',
        2,
        'PUBLISHED',
        now(),
        now(),
        now());

INSERT INTO question (topic_uuid, slug, question, reference_answer, explanation, question_type, level_id,
                      status, created_at, updated_at, published_at)
VALUES ((SELECT uuid FROM topic WHERE slug = 'concurrency'),
        'thread-creation-order',
        'Расположите основные действия при запуске потока в правильном порядке.',
        NULL,
        'Сначала создаётся объект Thread, затем вызывается start(), после чего JVM планирует выполнение метода run().',
        'ORDERING',
        2,
        'PUBLISHED',
        now(),
        now(),
        now());

INSERT INTO question_order_item (question_uuid, text, correct_order)
VALUES ((SELECT uuid FROM question WHERE slug = 'thread-creation-order'),
        'Создать объект Thread',
        1),
       ((SELECT uuid FROM question WHERE slug = 'thread-creation-order'),
        'Вызвать start()',
        2),
       ((SELECT uuid FROM question WHERE slug = 'thread-creation-order'),
        'Поток получает возможность начать выполнение',
        3),
       ((SELECT uuid FROM question WHERE slug = 'thread-creation-order'),
        'Выполняется run()',
        4);

INSERT INTO question_option (question_uuid, text, correct, sort_order)
VALUES ((SELECT uuid FROM question WHERE slug = 'which-type-is-immutable'),
        'String',
        TRUE,
        1),
       ((SELECT uuid FROM question WHERE slug = 'which-type-is-immutable'),
        'StringBuilder',
        FALSE,
        2),
       ((SELECT uuid FROM question WHERE slug = 'which-type-is-immutable'),
        'ArrayList',
        FALSE,
        3),
       ((SELECT uuid FROM question WHERE slug = 'which-type-is-immutable'),
        'HashMap',
        FALSE,
        4);

INSERT INTO question_option (question_uuid, text, correct, sort_order)
VALUES ((SELECT uuid FROM question WHERE slug = 'collection-interface-implementations'),
        'ArrayList',
        TRUE,
        1),
       ((SELECT uuid FROM question WHERE slug = 'collection-interface-implementations'),
        'LinkedList',
        TRUE,
        2),
       ((SELECT uuid FROM question WHERE slug = 'collection-interface-implementations'),
        'HashMap',
        FALSE,
        3),
       ((SELECT uuid FROM question WHERE slug = 'collection-interface-implementations'),
        'HashSet',
        FALSE,
        4);

INSERT INTO question_matching_pair (question_uuid, left_text, right_text, sort_order)
VALUES ((SELECT uuid FROM question WHERE slug = 'match-java-types'),
        'String',
        'Неизменяемая последовательность символов',
        1),
       ((SELECT uuid FROM question WHERE slug = 'match-java-types'),
        'ArrayList',
        'Динамический массив',
        2),
       ((SELECT uuid FROM question WHERE slug = 'match-java-types'),
        'HashMap',
        'Отображение ключей на значения',
        3),
       ((SELECT uuid FROM question WHERE slug = 'match-java-types'),
        'Thread',
        'Поток выполнения',
        4);
