CREATE TABLE topic
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        VARCHAR(150) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    parent_id   BIGINT,
    status      VARCHAR(20) NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT uk_topic_slug
        UNIQUE (slug),

    CONSTRAINT fk_topic_parent
        FOREIGN KEY (parent_id)
            REFERENCES topic (id),

    CONSTRAINT chk_topic_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX idx_topic_parent_id
    ON topic (parent_id);

CREATE INDEX idx_topic_status_sort
    ON topic (status, sort_order, id);